home/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(
    'home.views',
    url(r'^$', 'home', name='home'),
)

incubu/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'incubu.views.home', name='home'),
    # url(r'^incubu/', include('incubu.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^control/', include(admin.site.urls)),
    url(r'^$', include('home.urls')),
    url(r'^usuario/', include('usuarios.urls')),
    url(r'^acerca/$', TemplateView.as_view(template_name='home/acercade.html')),
)

usuarios/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'usuarios.views',
    url(r'^registra/$', 'registra', name='registra'),
    url(r'^escritorio/$', 'escritorio', name='escritorio'),
    url(r'^logout/$', 'logouts', name='logouts'),
    url(r'^add_key/$', 'add_key', name='add_key'),
    url(r'^edit_key/$', 'edit_key', name='edit_key'),
    url(r'^delete_key/$', 'delete_key', name='delete_key'),
    url(r'^configuracion/$', 'configuracion', name='configuracion'),
)

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User


class Account(models.Model):
    """Account class is the model for user accounts."""
    description = models.TextField(max_length=100)
    user_account = models.CharField(max_length=100, verbose_name='user account')
    pass_account = models.CharField(max_length=100, verbose_name='pass_account')
    user = models.ForeignKey(User)

usuarios/forms.py
from django import forms
from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from usuarios.models import Account


class UserCreateForm(UserCreationForm):
    """Form para creacion de Usuario"""
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)

    def clean(self):
        super(UserCreateForm, self).clean()
        cd = self.cleaned_data
        email = cd.get('email')
        username = cd.get('username')
        if email:
            try:
                User.objects.get(email=email)
                self._errors['email'] = "Email existente, escoger otro."
            except:
                pass
        if username:
            if '@' in username:
                self._errors['username'] = 'No se permite el @ en el Usuario'
        return cd


class AddAccount(forms.ModelForm):
    """Form para agregar ctas"""
    class Meta:
        model = Account
        fields = ("description", "user_account", "pass_account")


class UserEditForm(forms.ModelForm):
    """Custom Form para Configuracion de data del Usuario."""
    password_actual = forms.CharField(
        widget=forms.PasswordInput(), required=False)
    password = forms.CharField(
        widget=forms.PasswordInput(), required=False)
    repassword = forms.CharField(
        widget=forms.PasswordInput(), required=False)

    class Meta:
        model = User
        fields = ("username", "email")

    def __init__(self, *args, **kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)
        self.instance = getattr(self, 'instance', None)

    def clean(self):
        super(UserEditForm, self).clean()
        cd = self.cleaned_data
        username = cd.get('username')
        password_actual = cd.get('password_actual')
        password = cd.get('password')
        repassword = cd.get('repassword')
        email = cd.get('email')
        if email and email != self.instance.email:
            try:
                User.objects.get(email=email)
                self._errors['email'] = "Email existente, escoger otro."
            except:
                pass
        if password_actual or password or repassword:
            if auth.authenticate(username=username, password=password_actual):
                if password and repassword:
                    if password != repassword:
                        self._errors['password'] = 'Los passwords nuevos no coinciden.'
                else:
                    self._errors['password'] = "Debe introducir ambos password."
            else:
                self._errors['password_actual'] = "El password actual no es correcto."
        return cd

usuarios/views.py
import json
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from usuarios.forms import UserCreateForm, AddAccount, UserEditForm
from usuarios.models import Account


def registra(request):
    output = {}
    if request.method == 'POST':
        form_reg = UserCreateForm(data=request.POST)
        if form_reg.is_valid():
            username = request.POST.get('username')
            email = request.POST.get('email')
            password = request.POST.get('password1')
            userDB = User.objects.create_user(username, email, password)
            userDB.save()
            access = authenticate(username=username, password=password)
            login(request, access)
            return HttpResponseRedirect('/usuario/escritorio/')
        else:
            output['errors'] = 'Ha ocurrido un error favor de revisar el formulario'
    else:
        form_reg = UserCreateForm()
    output['usuario_registra'] = form_reg
    return render(request, "usuarios/registra.html", output)


@login_required
def escritorio(request):
    output = {}
    output['accounts'] = Account.objects.filter(user=request.user)
    output['add_account'] = AddAccount()
    return render(request, "usuarios/escritorio.html", output)


@login_required
def logouts(request):
    logout(request)
    return HttpResponseRedirect("/")


@login_required
def add_key(request):
    response = {}
    if request.is_ajax() and request.method == 'POST':
        description = request.POST.get('description')
        user_account = request.POST.get('user_account')
        pass_account = request.POST.get('pass_account')
        try:
            acc = Account(
                description=description,
                user_account=user_account,
                pass_account=pass_account,
                user=request.user)
            acc.save()
            response['estatus'] = True
        except Exception, e:
            response['estatus'] = False
            response['errors'] = e
        return HttpResponse(json.dumps(response))
    else:
        return HttpResponse(status=400)


@login_required
def edit_key(request):
    response = {}
    if request.is_ajax() and request.method == 'POST':
        description = request.POST.get('description')
        user_account = request.POST.get('user_account')
        pass_account = request.POST.get('pass_account')
        account_id = request.POST.get('account_id')
        try:
            acc = Account.objects.get(pk=account_id)
            acc.description = description
            acc.user_account = user_account
            acc.pass_account = pass_account
            acc.save()
            response['estatus'] = True
        except Exception, e:
            response['estatus'] = False
            response['errors'] = e
        return HttpResponse(json.dumps(response))
    else:
        return HttpResponse(status=400)


@login_required
def delete_key(request):
    response = {}
    if request.is_ajax() and request.method == 'POST':
        data_id = request.POST.get('data_id')
        try:
            Account.objects.get(id=data_id).delete()
            response['estatus'] = True
        except Exception, e:
            response['estatus'] = False
            response['errors'] = e
        return HttpResponse(json.dumps(response))
    else:
        return HttpResponse(status=400)


@login_required
def configuracion(request):
    output = {}
    output['estatus'] = False
    if request.method == "POST":
        user_edit = UserEditForm(request.POST, instance=request.user)
        if user_edit.is_valid():
            password_actual = request.POST.get('password_actual')
            password = request.POST.get('password')
            repassword = request.POST.get('repassword')
            user_edit.save()
            if password_actual and password and repassword:
                request.user.set_password(password)
                request.user.save()
            output['estatus'] = True
    else:
        user_edit = UserEditForm(instance=request.user)
    output['user_edit_form'] = user_edit
    return render(request, "usuarios/configuracion.html", output)

incubu/templates/usuarios/configuracion.html
{% extends "base.html" %}
{% block title %}Configuración{% endblock %}
{% if user.is_authenticated %}
    {% block js_app %}data-start="dashboard/escritorio"{% endblock %}
{% endif %}
{% block css %}
    <link href="/static/css/usuarios/usuarios.css" rel="stylesheet">
{% endblock %}
{% block content %}
<div id='escritorio'>
    <div class='row'>
        <div class='large-8 columns'>
            <h2>Configuración</h2>
        </div>
    </div>
    <div class="row">
        <div class='large-6 large-centered columns'>
            {% if estatus %}
                <div class="row">
                    <div class="large-12 columns">
                        <h3>Datos actualizados correctamente.</h3>
                    </div>
                </div>
            {% else %}
            <form action="/usuario/configuracion/" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="large-2 columns">
                    <label for="id_username" class="left inline">Usuario:</label>
                </div>
                <div class="large-10 columns">
                    {{user_edit_form.username}}
                    {% if user_edit_form.username.errors %}
                    <label class='msg_error_label' style="margin-bottom: 20px;">
                        {{user_edit_form.username.errors}}
                    </label>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="large-2 columns">
                    <label for="id_email" class="left inline">Email: </label>
                </div>
                <div class="large-10 columns">
                    {{user_edit_form.email}}
                    {% if user_edit_form.email.errors %}
                    <label class='msg_error_label' style="margin-bottom: 20px;">
                        {{user_edit_form.email.errors}}
                    </label>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="large-2 columns">
                    <label for="id_password_actual" class="left inline">Password Actual: </label>
                </div>
                <div class="large-10 columns">
                    {{user_edit_form.password_actual}}
                    {% if user_edit_form.password_actual.errors %}
                    <label class='msg_error_label' style="margin-bottom: 20px;">
                        {{user_edit_form.password_actual.errors}}
                    </label>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="large-2 columns">
                    <label for="id_password" class="left inline">Nuevo Password: </label>
                </div>
                <div class="large-10 columns">
                    {{user_edit_form.password}}
                    {% if user_edit_form.password.errors %}
                    <label class='msg_error_label' style="margin-bottom: 20px;">
                        {{user_edit_form.password.errors}}
                    </label>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="large-2 columns">
                    <label for="id_repassword" class="left inline">Repetir Password: </label>
                </div>
                <div class="large-10 columns">
                    {{user_edit_form.repassword}}
                </div>
            </div>

            <div class="row">
                <div class="large-12 columns right inline">
                    <input type="submit" class="small button" value="Actualizar"/>
                </div>
            </div>
            </form>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

incubu/templates/usuarios/escritorio.html
{% extends "base.html" %}
{% block title %}Escritorio{% endblock %}
{% if user.is_authenticated %}
    {% block js_app %}data-start="dashboard/escritorio"{% endblock %}
{% endif %}
{% block css %}
    <link href="/static/css/usuarios/usuarios.css" rel="stylesheet">
{% endblock %}
{% block content %}
<div id='escritorio'>
    <div class='row'>
        <div class='large-8 columns'>
            <h2 id="link_desktop" style="cursor:pointer;">Escritorio</h2>
            <a href="#" id="link_add_clave">Registrar Cuenta</a><br><br>
                <div id="init_clave">
                    {% if not accounts %}
                    <p>
                        <strong>* Introduce una frase con la cual seran encriptadas/desecriptadas tus claves. Recuerda
                        que esta sera tu frase de desencriptado y deberas recordarla siempre.</strong>
                    </p>
                    {% endif %}
                    <div class="row">
                        <button id="load_key" class="small button left" for="id_key" style="margin-left:18px;">Cargar Frase</button>
                        <div class="large-5 columns">
                            <input type="password" name="id_key" id="id_key" />
                        </div>
                        
                    </div>
                </div>
        </div>
    </div>
    <div class='row'>
        <div class='large-6 large-centered columns' id="table_keys" style="display:block;">
            <h2 style="color: #71C18B;">Cuentas</h2>
            <table id="accounts" class="bordered">
                <thead>
                    <tr>
                        <th>Descripcion</th>
                        <th>Usuario</th>
                        <th>Clave</th>
                        <th>Editar</th>
                        <th>Eliminar</th>
                    </tr>
                </thead>
                <tbody>
                    {% if accounts %}
                    {% for account in accounts %}
                        <tr class="{{account.id}}">
                            <td class="tbl_description" data="{{account.description}}">
                                {{account.description|truncatechars:10}}
                            </td>
                            <td class="tbl_user" data="{{account.user_account}}">
                                {{account.user_account|truncatechars:10}}
                            </td>
                            <td class="tbl_pass" data="{{account.pass_account}}">
                                {{account.pass_account|truncatechars:10}}
                            </td>
                            <td><img class="edit_account" data-description="{{account.description}}" data-user="{{account.user_account}}" data-pass="{{account.pass_account}}" data-acc-id="{{account.id}}" src="/static/images/usuario/edit.png" width="20"></td>
                            <td><img class="delete_account" data="{{account.id}}" src="/static/images/usuario/delete.png" width="20"></td>
                        </tr>
                    {% endfor %}
                    {% else %}
                        <!-- <tr><td colspan="5">No tienes cuentas almacenadas.</td></tr> -->
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
    <div class='row'>
        <div class='large-6 large-centered columns' id="add_key" style="display:none;">
            <h2 style="color: #71C18B;">Registrar cuenta nueva</h2>
            <div class="row">
                <div class="large-2 columns">
                    <label for="id_description" class="left inline">Descripcion: </label>
                </div>
                <div class="large-10 columns">
                    {{add_account.description}}
                </div>
            </div>
            <div class="row">
                <div class="large-2 columns">
                    <label for="id_user_account" class="left inline">Usuario: </label>
                </div>
                <div class="large-10 columns">
                    {{add_account.user_account}}
                </div>
            </div>
            <div class="row">
                <div class="large-2 columns">
                    <label for="id_pass_account" class="left inline">Clave: </label>
                </div>
                <div class="large-10 columns">
                    {{add_account.pass_account}}
                </div>
            </div>
            <div class="row">
                <div class="large-12 columns right inline">
                    <button class="small button" id="submit_add_clave" data-type="add">
                        Registrar
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

incubu/templates/usuarios/registra.html
{% extends "base.html" %}
{% block css %}
    <link href="/static/css/usuarios/usuarios.css" rel="stylesheet">
{% endblock %}
{% block content %}
<div id='registra'>
        <div class='row'>
            <div class='row'>
                <div class='large-8 large-centered columns'>
                    <h2>Registrate</h2>
                    <p>Empieza a almacenar de manera segura todas tus claves.
                    </p>
                </div>
            </div>
            <div class='row'>
                <div class='large-5 large-centered columns'>
                    <form id="form_contact" method="POST" >
                        {% csrf_token %}
                        <div class="row">
                            <div class="large-2 columns">
                                <label for="id_username" class="left inline">Usuario: </label>
                            </div>
                            <div class="large-10 columns">
                                {{usuario_registra.username}}
                                {% if usuario_registra.username.errors %}
                                <label class='msg_error_label'>
                                    {{usuario_registra.username.errors}}
                                </label>
                                {% endif %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="large-2 columns">
                                <label for="id_email" class="left inline">Correo: </label>
                            </div>
                            <div class="large-10 columns">
                                {{usuario_registra.email}}
                                {% if usuario_registra.email.errors %}
                                <label class='msg_error_label'>
                                    {{usuario_registra.email.errors}}
                                </label>
                                {% endif %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="large-2 columns">
                                <label for="id_password1" class="left inline">Clave: </label>
                            </div>
                            <div class="large-10 columns">
                                {{usuario_registra.password1}}
                                {% if usuario_registra.password1.errors %}
                                    <label class='msg_error_label'>
                                        {{usuario_registra.password1.errors}}
                                    </label>
                                {% endif %}
                            </div>
                        </div>
                        <div class="row">
                            <div class="large-2 columns">
                                <label for="id_password2" class="left inline">Repite Clave: </label>
                            </div>
                            <div class="large-10 columns">
                                {{usuario_registra.password2}}
                                {% if usuario_registra.password2.errors %}
                                    <label class='msg_error_label'>
                                        {{usuario_registra.password2.errors}}
                                    </label>
                                {% endif %}
                            </div>
                        </div>
                        {%if errors %}
                            <label class='msg_error'>
                                {{errors}}
                            </label><br>
                        {% endif %}
                        <div class="row">
                                <div class="large-12 columns right inline">
                                    <input type="submit" class="small button" value='Registrar' />
                                </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}